# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dimFeather <- function(path) {
    .Call('feather_dimFeather', PACKAGE = 'feather', path)
}

metadataFeather <- function(path) {
    .Call('feather_metadataFeather', PACKAGE = 'feather', path)
}

readFeather <- function(path) {
    .Call('feather_readFeather', PACKAGE = 'feather', path)
}

writeFeather <- function(df, path) {
    invisible(.Call('feather_writeFeather', PACKAGE = 'feather', df, path))
}

