# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

metadataFeather <- function(path) {
    .Call('_feather_metadataFeather', PACKAGE = 'feather', path)
}

openFeather <- function(path) {
    .Call('_feather_openFeather', PACKAGE = 'feather', path)
}

closeFeather <- function(feather) {
    invisible(.Call('_feather_closeFeather', PACKAGE = 'feather', feather))
}

rowsFeather <- function(feather) {
    .Call('_feather_rowsFeather', PACKAGE = 'feather', feather)
}

coldataFeather <- function(feather, indexes) {
    .Call('_feather_coldataFeather', PACKAGE = 'feather', feather, indexes)
}

writeFeather <- function(df, path, description) {
    invisible(.Call('_feather_writeFeather', PACKAGE = 'feather', df, path, description))
}

