// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// feather_dim
IntegerVector feather_dim(std::string path);
RcppExport SEXP feather_feather_dim(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    __result = Rcpp::wrap(feather_dim(path));
    return __result;
END_RCPP
}
// feather_metadata
CharacterVector feather_metadata(std::string path);
RcppExport SEXP feather_feather_metadata(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    __result = Rcpp::wrap(feather_metadata(path));
    return __result;
END_RCPP
}
